export enum Code {
  MYSQL = "MySQL",
  PHP = "PHP",
  JAVASCRIPT = "JavaScript",
  TYPESCRIPT = "TypeScript",
  SMARTY = "Smarty PHP",
  NODE = "NodeJS",
  REACT = "ReactJS",
  VUE = "VueJS",
  API = "API",
  PUG = "PUG",
  CSS = "CSS",
  SCSS = "SCSS",
  MONGODB = "MongoDB",
  EXPRESS = "ExpressJS",
  TWIG = "Twig",
  BOOTSTRAP = "Bootstrap",
  SYMFONY = "Symfony",
  MONGOOSE = "Mongoose",
  HTML = "html",
  PRESTASHOP = "PrestaShop",
  WEBPACK = "Webpack",
  REDUX = "Redux",
}
